### ISSUE TITLE
FAI index input parameter

### ISSUE THREAD

**Issue by arvindsundaram** [genomic-medicine-sweden/tomte#119]
### Description of feature

Nf-core supported '--fasta_fai' in not supported in tomte.

**Comment by Lucpen** [comment]
Hi Arvnid,

it should be `--fai` instead of `--fasta_fai`, try it out and let me know if you keep having problems.
I hope it helps,

Lucía

**Comment by arvindsundaram** [comment]
That's correct - it works. Sorry my mistake :)
