### ISSUE TITLE
vcfs with only one variant per line so that they can be handled by Scout

### ISSUE THREAD

**Issue by Lucpen** [genomic-medicine-sweden/tomte#125]
### Description of the bug

The vcfs from tomte are not compatible with scout. Scout requires only one alternative per line
This can be fixed by:

```
bcftools norm -m -both input.vcf.gz > output.vcf
bgzip output.vcf
tabix  output.vcf.gz
```

**Comment by jemten** [comment]
inspiration here 
https://github.com/nf-core/raredisease/blob/1489b71cc0e15ade7e98a834df0170b650aa932c/subworkflows/local/variant_calling/call_snv_deepvariant.nf#L47
