### ISSUE TITLE
Give systematic naming to columns from DROP output

### ISSUE THREAD

**Issue by Lucpen** [genomic-medicine-sweden/tomte#131]
### Description of the bug

Column naming is not so systematic (many in camel case, some that useunderscores, some that mix, some with ALL CAPS, some all lower without any separators). Also some unused columns by the looks of it, esp for fraser? Like GENE_COUNTS_FILE, SPLICE_COUNTS_DIR, DNA_ID aso.

**Comment by dnil** [comment]
I have a feeling the ideal would be to pass this one level up to make it match the DROP documentation, but having all in one convention would sure be pretty!

**Comment by Lucpen** [comment]
The captails separated by _ come form the annotation table, I could make them into camel case and that way everything would match
