### ISSUE TITLE
Non-ACGTN reference allele

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#145]
### Description of the bug

When running Tomte, it crashes for me at the `SPLIT_MULTIALLELICS` step due to non-regular base "B" being present.

It seems similar to the error found here: https://github.com/samtools/bcftools/issues/473 It seems to be due to `mpileup` sometimes generating the `B` base.

I further checked the reference genome and BAM file for this region. No non ACGTN letters were found there.

Here is the error:

```
ERROR ~ Error executing process > 'GENOMICMEDICINESWEDEN_TOMTE:TOMTE:CALL_VARIANTS:SPLIT_MULTIALLELICS (<ID>)'

Caused by:
  Process `GENOMICMEDICINESWEDEN_TOMTE:TOMTE:CALL_VARIANTS:SPLIT_MULTIALLELICS (<ID>)` terminated with an error exit status (255)


Command executed:

  bcftools norm \
      --fasta-ref GCA_000001405.15_GRCh38_no_alt_analysis_set_chr_masked.fna \
      --output <ID>_norm.vcf.gz\
      --output-type z --multiallelics -both \
      --threads 16 \
      <ID>.vcf.gz

  cat <<-END_VERSIONS > versions.yml
  "GENOMICMEDICINESWEDEN_TOMTE:TOMTE:CALL_VARIANTS:SPLIT_MULTIALLELICS":
      bcftools: $(bcftools --version 2>&1 | head -n1 | sed 's/^.*bcftools //; s/ .*$//')
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  Non-ACGTN reference allele at chr3:16902879 .. REF_SEQ:'TGTGNG' vs VCF:'TGTGBG'

Work dir:
  <workdir>/tomte/87/994c3113cd903794f7c9f5652d7379

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details
```

Looking at that position in the input VCF, there is indeed a "B" present:

```
chr3    16902879        .       TGTGBG  TG      38.1334 .       INDEL;IDV=6;IMF=0.0521739;DP=7;VDB=0.400625;SGB=-0.590765;RPBZ=1.17689;MQBZ=0;MQSBZ=0;SCBZ=2.88819;MQ0F=0;AC=2;AN=2;DP4=1,0,2,3;MQ=20   GT:PL   1/1:65,9,0
```

I will continue investigating, starting with rerunning using the latest version of Tomte (I realized I ran using a version prior to the update of bcftools).

**Comment by Jakob37** [comment]
Sorry, this comes originally from our reference. Closing!

**Comment by Anacristina0914** [comment]
Hello, 

I have been experiencing a similar issue running the sarek v3.4.2 pipeline, where only some of the VCF ( 2 out of my 3 samples) generated by `mpileup` show ambiguous bases "R" in chromosome 7 (genome build GRCh38). I have seen this issue once more in a specific region of chromosome 3. I checked the igenomes reference from https://support.illumina.com/sequencing/sequencing_software/igenome.html, and found that the "R" bases are indeed coming from the reference itself. Does your pipeline uses the same reference from the s3 aws bucket (s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/Chromosomes/) ? could this be part of the same issue?

Thanks in advance!

**Comment by Jakob37** [comment]
> Hello,
> 
> I have been experiencing a similar issue running the sarek v3.4.2 pipeline, where only some of the VCF ( 2 out of my 3 samples) generated by `mpileup` show ambiguous bases "R" in chromosome 7 (genome build GRCh38). I have seen this issue once more in a specific region of chromosome 3. I checked the igenomes reference from https://support.illumina.com/sequencing/sequencing_software/igenome.html, and found that the "R" bases are indeed coming from the reference itself. Does your pipeline uses the same reference from the s3 aws bucket (s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/Chromosomes/) ? could this be part of the same issue?
> 
> Thanks in advance!

It looks like it could be the same or a similar issue. I don't think we have downloaded our reference genome from that exact location, but it might very well be same / similar anyway.

I did a counting of all letters in our reference genome and found that there is a bunch of non ACGTNs:

```
defaultdict(<class 'int'>, {'N': 166087682, 'T': 868645206, 'A': 866149498, 'C': 598435124, 'G': 600604937, 'M': 8, 'R': 26, 'Y': 33, 'W': 13, 'K': 8, 'B': 2, 'S': 4})
```

Currently I am trying out an updated version where I have replaced non ACGTs with N:

```
sed '/^[^>]/ s/[^ACGTNacgtn]/N/g' orig.fna > updated_only_acgtn.fna
```

**Comment by Anacristina0914** [comment]
Thank you for your answer, this is very helpful!

**Comment by mi3112** [comment]
Hello guys @Jakob37 @Anacristina0914,

I'm using nf-core/sarek and I'm facing the same problem — actually, Ana’s post is what brought me here. I followed Jakob’s recommendation and then used the "update_reference" to run `BaseRecalibrator` step.

Now I’m getting the following error:

`The MD5 for the reference failed to validate against the expected value c0f6837f8f940c83d816ed3d1f2439e1. This indicates that the supplied reference is not the one originally used to create the CRAM.`

Has anyone encountered this issue after using update the reference?
Is there a recommended way to ensure the reference FASTA and its associated files (dict, fai, etc.) are fully consistent with the original CRAM?

Thanks in advance!

**Comment by Jakob37** [comment]
> Hello guys [@Jakob37](https://github.com/Jakob37) [@Anacristina0914](https://github.com/Anacristina0914),
> 
> I'm using nf-core/sarek and I'm facing the same problem — actually, Ana’s post is what brought me here. I followed Jakob’s recommendation and then used the "update_reference" to run `BaseRecalibrator` step.
> 
> Now I’m getting the following error:
> 
> `The MD5 for the reference failed to validate against the expected value c0f6837f8f940c83d816ed3d1f2439e1. This indicates that the supplied reference is not the one originally used to create the CRAM.`
> 
> Has anyone encountered this issue after using update the reference? Is there a recommended way to ensure the reference FASTA and its associated files (dict, fai, etc.) are fully consistent with the original CRAM?
> 
> Thanks in advance!

I haven't encountered this exact error. But it looks like some software is detecting that the reference that you are supplying now is different (i.e. a different md5sum) than when used to generate your CRAM file.

I suspect you either would need to somehow stick with the original reference for that CRAM, or regenerate the CRAM by aligning against the updated reference.
