### ISSUE TITLE
mRNA and rRNA percentages missing from MultiQC output

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#150]
### Description of the bug

Previously the MultiQC output from Tomte included mRNA and rRNA percentage values.

Since the latest updates, these are no longer part of the MultiQC output.

I could see in my run that the values were calculated, just not included in MultiQC (i.e. not put in the `multiqc_data` folder).

It might be an issue with the recent MultiQC issues. It was recently discussed, but claimed to be fixed: https://github.com/MultiQC/MultiQC/issues/2608

I have tried the current MultiQC version (1.22.3) and also swapping the container to the most recent version (1.23).

Needs more investigation though, to understand why the CollectRnaSeqMetrics files are calculated but not put in the `multiqc_data` folder.

### Command used and terminal output

```console
Running the dev branch, commit: 00e5eb320ebb6a5a913ff136f45adf7171c7a75a
```

**Comment by Lucpen** [comment]
Thanks for making an issue, I assume that updating to the newest version of the container didn't help, right?

**Comment by Jakob37** [comment]
> Thanks for making an issue, I assume that updating to the newest version of the container didn't help, right?

No exactly, assuming that I did everything correctly, using the latest MultiQC version (1.23) did not help.

**Comment by Lucpen** [comment]
This should be solved when merging the new template as the multiQC version will be updated to 1.25
In test runs the produced multiQC includes both mRNA and rRNA 😄
