### ISSUE TITLE
Non-HGNC symbols in the hgncSymbol column

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#161]
### Description of feature

Not really an `enhancement`, rather a question.

In the DROP output, there is a column `hgncSymbol` which is important for loading the cases into Scout.

In ~10% of the cases in my run, I get `ENS` IDs instead.

Not sure whether a bug, but wondering how to deal with them. How do you guys deal with those?

Some examples:

![hgnc_drop](https://github.com/user-attachments/assets/d56e7134-30b2-4511-87ff-ad877da219b2)

**Comment by Lucpen** [comment]
Hi Jakob,
I we are not getting those, that probably comes from your gene annotation gtf file

**Comment by Lucpen** [comment]
It looks like it happens on lncRNA, maybe those don't have proper gene names?

**Comment by Jakob37** [comment]
Yes, looks like it is coming from the gene annotation gtf file. We are using the latest Gencode (v46, https://www.gencodegenes.org/human/release_46.html). Might be that some genes simply haven't HGNC symbols yet.

Which annotations are you guys using?

Closing, not a Tomte issue.

**Comment by Lucpen** [comment]
At the moment we are still on genocde v37, but hopefully will switch to v46 soon. We are building databases and all of that...

**Comment by Jakob37** [comment]
OK I see! Then I guess you guys will have the same ENS-ID issue

**Comment by Lucpen** [comment]
Yes, thanks for the heads up!
