### ISSUE TITLE
Crash in 03_filter_expression_FraseR.R when running with external counts

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#171]
### Description of the bug

I am running into the following error:

```
Error in FUN(X[[i]], ...) : 
  Can not find provided sampleID in count data. Missing IDs: .... (all external IDs)
```

Digging into the code into the called function `mergeExternalData.R` inside the `FRASER` package, it seems to be crashing here:

```
  extCts <- lapply(reqNames, function(id){
    gr <- makeGRangesFromDataFrame(fread(countFiles[id]), keep.extra.columns=TRUE)
    seqlevelsStyle(gr) <- seqlevelsStyle(fds) #force fds style onto external counts
    if(any(!sampleIDs %in% colnames(mcols(gr)))){
      stop("Can not find provided sampleID in count data. Missing IDs: ",
           paste(collapse=", ",
                 sampleIDs[!sampleIDs %in% colnames(mcols(gr))]))
    }
    gr[,sampleIDs]
  })
```

Specifically in the `sampleIDs` check.

Looking into the FRASER files used they look like this:

```
seqnames        start   end     strand  as.array(x, drop = TRUE)
chr1    12228   12612   +       1
chr1    12722   13220   +       1
chr1    827776  829002  +       5
chr1    829105  841199  +       10
chr1    847807  851926  +       4
chr1    829105  847653  +       10
```

It is looking among these columns for the sample ID. Looks like the `as.array(x, drop = TRUE)` comes from when originally preparing the external reference for FRASER.

I'll continue to investigate.

**Comment by Lucpen** [comment]
Hi Jakob,

how does your annotation file look?

**Comment by Lucpen** [comment]
I don't know id it could make a difference, but what version of DROP did you use to build your DB?

Regarding the reference,  if you supply the same input parameters as before, it should run with the same reference.

**Comment by Jakob37** [comment]
Something seems to have led to the exported counts from AS I am using looking like this:

```
seqnames        start   end     strand  as.array(x, drop = TRUE) 
chr1    12228   12612   +       1                                
chr1    12722   13220   +       1                                
chr1    827776  829002  +       5                                
chr1    829105  841199  +       2                                
chr1    847807  851926  +       4                                
chr1    829105  847653  +       7                                
chr1    855122  856448  +       4                                
chr1    850352  851926  +       1                                
chr1    827850  829002  +       2                                
```

Compared to this, which I see in one of the work dirs:

```
seqnames  start  end    strand  SAMPLE1  SAMPLE2 ... (+50 samples)
chr1      12228  12612  +       1        3      
chr1      12722  13220  +       1        5      
chr1      13053  13220  +       0        0      
chr1      30040  30563  +       0        0      
```

Same DROP version used (1.4.0). Will answer the rest of the questions tomorrow.

Need to run and grab my kid now. Will look more into this tomorrow!

**Comment by Jakob37** [comment]
Looks like it worked nicely using the correct splice db folder.

I am a bit confused on what went wrong in the initial db. I see now that the exported DB for PAX looks OK.

I think I'll close this issue. I'll reopen and come back with more info if I encounter the issue again.
