### ISSUE TITLE
Gene body coverage calculations

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#176]
### Description of feature

We have been sitting down with our CLGs and discussed what QC metrics they want to use from Tomte.

One metric they use for other RNA-seq projects (and would like to use here as well) is gene body coverage.

It can be calculated using a script present in RSeQC (https://rseqc.sourceforge.net/) and likely in many other ways.

If you think this would be valuable to have in Tomte as an optional step, then I can look into adding it.

**Comment by jemten** [comment]
We mainly use Picard CollectRNAseqmetrics (https://broadinstitute.github.io/picard/picard-metric-definitions.html#RnaSeqMetrics). That module supplies the datapoints to have mutliqc draw a genebody coverage plot. You can supply it with an option to have it produce a pdf with genebody coverage as well, `--CHART_OUTPUT <FILE>` . 

from multiqc:
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/a61538d3-84cb-4424-8efc-596ab7f09fd2">

But I have no issues with adding an optional extra QC if you think it's needed :)

**Comment by Jakob37** [comment]
> We mainly use Picard CollectRNAseqmetrics (https://broadinstitute.github.io/picard/picard-metric-definitions.html#RnaSeqMetrics). That module supplies the datapoints to have mutliqc draw a genebody coverage plot. You can supply it with an option to have it produce a pdf with genebody coverage as well, `--CHART_OUTPUT <FILE>` .
> 
> from multiqc: <img alt="image" width="1143" src="https://private-user-images.githubusercontent.com/3168925/378824323-a61538d3-84cb-4424-8efc-596ab7f09fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTkwNTcsIm5iZiI6MTcyOTU5ODc1NywicGF0aCI6Ii8zMTY4OTI1LzM3ODgyNDMyMy1hNjE1MzhkMy04NGNiLTQ0MjQtOGVmYy01OTZhYjdmMDlmZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjJUMTIwNTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQ1Nzg2NmQzM2RlZTM2YjA0ODNkYzM2MGRhMjkyMjZjNTIwZGRmZDc0ZTRiNWRmM2ViNDA1MmUzNDI3ZGRkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tkVlihcTnWvCzynGx5PCvH8Zv4oK0IMFXa6DckhtkR4">
> 
> But I have no issues with adding an optional extra QC if you think it's needed :)

OK, I see! We have no special attachment to the RSeQC script. More of a slight aversion. Great to hear this is already calculated 😊
