### ISSUE TITLE
Run Peddy as part of Tomte

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#186]
### Description of feature

We are looking into running Peddy to run a sex check on the RNA-seq samples.

I did a quick manual run on the current VCF output. Seems to work fine.

Would it make sense to include this in Tomte? I would be happy to PR. 

I realize you guys probably do a sex check on DNA-level and use that for display in Scout. It is a bit up in the air how we intend to approach DNA + RNA in the future, but seems we would want to have the ability to check sex on RNA either way.

**Comment by jemten** [comment]
Sounds good to me! If someone finds it annoying we can always add a switch later so that it can be skipped.
