### ISSUE TITLE
Calculate hemoglobin percentage in Tomte

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#187]
### Description of feature

We realized that we have a large variation of percentage of reads mapping to hemoglobin in our PAX samples (5-30%) which subsequently correlates to a number of QC metrics (multimapping, GC).

Thus we want to monitor the hemoglobin content to be easily follow up on this in the future, and thus have this as one of our QC values.

So far I have calculated this fraction from the STAR output (`sample.ReadsPerGene.out.tab`) using a simple Python script.

Would this make sense to include in Tomte? As an optional extra calculation. (Alternatively I can add it in our "post-processing pipeline").

**Comment by jemten** [comment]
It sounds pretty useful to me. What do you think @Lucpen?

**Comment by Jakob37** [comment]
OK, nice! Then I'll add it to Tomte.
