### ISSUE TITLE
Maintaining a site-specific profile in offline mode

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#191]
### Description of feature

Might be a broader nf-core issue, but thought I would start asking here.

We have a CMD-specific profile used when running Tomte, which is added to `nextflow.config`. This is currently maintained as a non-commited change in the repo. I.e.:

```
[jakob@rs-fe1 tomte]$ git diff nextflow.config            
diff --git a/nextflow.config b/nextflow.config            
index 025ca1b..1aee4bf 100644                             
--- a/nextflow.config                                     
+++ b/nextflow.config                                     
@@ -207,6 +207,7 @@ profiles {                            
     }                                                    
     test      { includeConfig 'conf/test.config'      }  
     test_full { includeConfig 'conf/test_full.config' }  
+    cmd       { includeConfig 'conf/cmd.config' }        
 }                                                        
```

Furthermore, the `conf/cmd.config` file is also present as an untracked file in the repo.

```
[jakob@rs-fe1 tomte]$ git status                                             
# On branch dev                                                              
# Changes not staged for commit:                                             
#   (use "git add <file>..." to update what will be committed)               
#   (use "git checkout -- <file>..." to discard changes in working directory)
#                                                                            
#       modified:   nextflow.config                                          
#                                                                            
# Untracked files:                                                           
#   (use "git add <file>..." to include in what will be committed)           
#                                                                            
#       conf/cmd.config                                                      
no changes added to commit (use "git add" and/or "git commit -a")            
```

I would like to find a solution where we don't need to `git stash` and `git stash pop` before and after each `git pull` 🤔 How do you guys deal with this?

There seems to be support for having custom configs, but this does not seem to be intended to work offline, looking at the following line in `nextflow.config`.

```
includeConfig !System.getenv('NXF_OFFLINE') && params.custom_config_base ? "${params.custom_config_base}/nfcore_custom.config" : "/dev/null"
```

**Comment by jemten** [comment]
Ah that sounds annoying :) 
We have our configs in a separate github repository for version control. On updates of the configs we do sync to our hpc and then when running tomte we use the full path to that config. Something like this:

`nextflow run path/to/tomte -config /path/to/our/config -params-file /path/to/params.yaml`. 

The reason being that we want to be able to update the config without having to do a new release of the pipeline. 

If that doesn't work for you we can look into modifying that includeConfig statement to work offline. Or if you prefer to have the config coupled with the pipeline to have a folder in conf with the `cmd` config.

**Comment by Jakob37** [comment]
> Ah that sounds annoying :) We have our configs in a separate github repository for version control. On updates of the configs we do sync to our hpc and then when running tomte we use the full path to that config. Something like this:
> 
> `nextflow run path/to/tomte -config /path/to/our/config -params-file /path/to/params.yaml`.
> 
> The reason being that we want to be able to update the config without having to do a new release of the pipeline.
> 
> If that doesn't work for you we can look into modifying that includeConfig statement to work offline. Or if you prefer to have the config coupled with the pipeline to have a folder in conf with the `cmd` config.

I see! Yes, I also keep the config version controlled separately, linking it in. I think using the `-config` flag would work nicely. Thanks!
