### ISSUE TITLE
Add an optional column for sex in DROP annotation

### ISSUE THREAD

**Issue by Lucpen** [genomic-medicine-sweden/tomte#60]
### Description of feature

Add an optional column for sex in DROP annotation

**Comment by Jakob37** [comment]
This would be useful for us in Lund as well!

**Comment by Jakob37** [comment]
I got this running in Lund I think. I can put up a PR when #147 is merged!

**Comment by Lucpen** [comment]
Amazing! We might still take a week or so before the merge, but I hope that not much longer

**Comment by Jakob37** [comment]
Sounds good! No hurry from our side, running in my own branch for now.

**Comment by Jakob37** [comment]
I'll give this a go now!

**Comment by Lucpen** [comment]
Sounds great! 🤩
